### ISSUE TITLE
Welcome c0d3m0nk3y

### ISSUE THREAD

**Issue by deeredman1991** [twitchplayskh/Emuchat#4]
Welcome to the dev team. 

Ty for taking up the gauntlet on this. 👍 twitchplayskh said you had some questions for me so, fire away.

My advise would be to run a major refactoring pass or two over the code. I worked on this back when I was REALLY bad at python and programming in general so it REALLY needs to be organized better if you guys plan to scale it out. :)

**Comment by codemonkeyiow** [comment]
Refactoring might be a good idea.  I'm going to fiddle for a bit in the current state, get comfortable with the current functionality and bugs, then I'll get an idea of how to structure it.

Thank you for the warm welcome.
